import psycopg2
import os
from dotenv import load_dotenv

# Load env from parent dir if needed, but assuming it's in the same dir for now
load_dotenv()

DB_URL = os.getenv("SUPABASE_DB_URL")

def init_db():
    if not DB_URL:
        print("Error: SUPABASE_DB_URL not found in .env")
        return

    commands = [
        # 1. Create profiles table
        """
        CREATE TABLE IF NOT EXISTS public.profiles (
            id UUID PRIMARY KEY REFERENCES auth.users ON DELETE CASCADE,
            email TEXT,
            full_name TEXT,
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
        );
        """,
        # 2. Create agent_mappings table
        """
        CREATE TABLE IF NOT EXISTS public.agent_mappings (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            agent_id TEXT NOT NULL,
            user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
        );
        """,
        # 3. Create a trigger function to handle new user signups
        """
        CREATE OR REPLACE FUNCTION public.handle_new_user()
        RETURNS TRIGGER AS $$
        BEGIN
          INSERT INTO public.profiles (id, email, full_name)
          VALUES (new.id, new.email, new.raw_user_meta_data->>'full_name');
          RETURN new;
        END;
        $$ LANGUAGE plpgsql SECURITY DEFINER;
        """,
        # 4. Create the trigger
        """
        DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
        CREATE TRIGGER on_auth_user_created
          AFTER INSERT ON auth.users
          FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
        """,
        # 5. Enable RLS on agent_mappings
        "ALTER TABLE public.agent_mappings ENABLE ROW LEVEL SECURITY;",
        # 6. Policy for users to see their own mappings
        """
        DROP POLICY IF EXISTS "Users can view their own agent mappings" ON public.agent_mappings;
        CREATE POLICY "Users can view their own agent mappings"
          ON public.agent_mappings FOR SELECT
          USING (auth.uid() = user_id);
        """,
        # 7. Policy for users to insert their own mappings
        """
        DROP POLICY IF EXISTS "Users can insert their own agent mappings" ON public.agent_mappings;
        CREATE POLICY "Users can insert their own agent mappings"
          ON public.agent_mappings FOR INSERT
          WITH CHECK (auth.uid() = user_id);
        """
    ]

    try:
        conn = psycopg2.connect(DB_URL)
        cur = conn.cursor()
        for command in commands:
            print(f"Executing: {command[:50]}...")
            cur.execute(command)
        conn.commit()
        cur.close()
        conn.close()
        print("Database initialized successfully!")
    except Exception as e:
        print(f"An error occurred: {e}")

if __name__ == "__main__":
    init_db()
